# Generated by Django 3.0.8 on 2020-12-07 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_downvotes', to='core.DownVote'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvotes',
            field=models.ManyToManyField(blank=True, null=True, related_name='user_upvotes', to='core.UpVote'),
        ),
    ]
